apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "customer-api"
  description: "Customer Manager API"
  annotations:
    github.com/project-slug: veecode-homolog/customer-api
    backstage.io/techdocs-ref: dir:.
    kong-manager/service-name: customer-api.customer-api-service.8080
    kong-manager/instance: kong-poc
    kong-manager/spec: openapi-swagger.yaml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - customer-api