apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-api
  title: customer-api
  publishedAt: "2024-06-13 19:34:01"
  description: Customer Manager API
  tags:
    - app
    - spec
    - demo
spec:
  type: openapi
  lifecycle: production
  owner: admin
  definition: |-
    openapi: 3.0.1
    info:
      title: Customer API
      description: API for managing customers
      version: 1.0.0
    servers:
      - url: https://customer.cluster-k8s-playrole.vkpr.platform.vee.codes
    paths:
      /customers:
        post:
          summary: Create a new customer
          requestBody:
            required: true
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Name of the customer"
                    email:
                      type: string
                      description: "Email of the customer"
                  required:
                    - name
                    - email
          responses:
            '200':
              description: Customer created successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                      customer:
                        $ref: '#/components/schemas/Customer'
            '400':
              description: Bad Request
            '500':
              description: Internal Server Error

